-- =========================================================
-- Fulfilment Operations Data Model Setup
-- This section creates the schema and core operational tables
-- used throughout the fulfilment analytics project.
-- =========================================================

-- Create dedicated schema for operations data
CREATE SCHEMA ops;

-- =========================================================
-- ORDERS TABLE
-- Stores core order-level information used for SLA and
-- fulfilment performance analysis
-- =========================================================

CREATE TABLE IF NOT EXISTS ops.orders (
    order_id BIGINT PRIMARY KEY,              -- unique order identifier
    order_date DATE,                          -- order placement date
    customer_country VARCHAR(100),            -- customer location
    destination_country VARCHAR(100),         -- delivery destination
    hub_id INT,                               -- fulfilment hub processing the order
    product_category VARCHAR(100),            -- product category
    order_value NUMERIC(10,2),                -- revenue generated by the order
    priority_flag VARCHAR(20),                -- indicates express/priority orders
    promised_delivery_date DATE               -- SLA commitment for delivery
);


-- =========================================================
-- FULFILMENT EVENTS TABLE
-- Tracks order progression across fulfilment stages
-- =========================================================

CREATE TABLE IF NOT EXISTS ops.fulfilment_events (
    event_id BIGSERIAL PRIMARY KEY,           -- unique event identifier
    order_id BIGINT,                          -- associated order
    stage_name VARCHAR(100),                  -- fulfilment stage (Intake, Packing, QC, Shipping, Delivery)
    stage_start_time TIMESTAMP,               -- stage start timestamp
    stage_end_time TIMESTAMP,                 -- stage completion timestamp
    status VARCHAR(50),                       -- stage status
    hub_id INT,                               -- hub processing this stage
    FOREIGN KEY (order_id) REFERENCES ops.orders(order_id)  -- maintain referential integrity
);


-- =========================================================
-- HUBS TABLE
-- Contains metadata about fulfilment hubs and their capacity
-- =========================================================

CREATE TABLE ops.hubs (
    hub_id INT PRIMARY KEY,                   -- unique hub identifier
    hub_name VARCHAR(50),                     -- hub name
    hub_country VARCHAR(10),                  -- country where hub is located
    capacity_per_day INT                      -- max orders the hub can process daily
);


-- =========================================================
-- SHIPPING TABLE
-- Stores logistics partner details and shipment cost
-- =========================================================

CREATE TABLE ops.shipping (
    shipped_id BIGSERIAL PRIMARY KEY,         -- shipment record id
    order_id INT,                             -- associated order
    shipping_partner VARCHAR(50),             -- logistics provider
    shipping_zone VARCHAR(10),                -- delivery region classification
    weight_bucket VARCHAR(20),                -- shipment weight category
    shipping_cost NUMERIC(10,2),              -- logistics cost per shipment
    FOREIGN KEY (order_id) REFERENCES ops.orders(order_id)
);


-- =========================================================
-- RETURNS TABLE
-- Tracks returned orders and refund information
-- =========================================================

CREATE TABLE IF NOT EXISTS ops.returns (
    return_id BIGSERIAL PRIMARY KEY,          -- return record identifier
    order_id INT,                             -- returned order
    return_reason VARCHAR(50),                -- reason for return
    return_request_date DATE,                 -- return request date
    refund_amount NUMERIC(10,2),              -- refunded amount
    FOREIGN KEY (order_id) REFERENCES ops.orders(order_id)
);


-- =========================================================
-- SLA TABLE
-- Defines stage-level service level agreements
-- =========================================================

CREATE TABLE IF NOT EXISTS ops.sla (
    stage_name VARCHAR(20),                   -- fulfilment stage
    sla_hours INT                             -- SLA threshold in hours
);

-- =========================================================
-- Data Validation & Quality Checks
-- NOTE:
-- The tables in this schema are populated using a Python
-- data generation script which simulates fulfilment operations.
-- SQL is used here to validate data integrity before analysis.
-- =========================================================


-- Create secondary schema (used for Python-generated tables if needed)
CREATE SCHEMA ops1; - this was created just to check how data is added from python directly


-- Set default schema for easier table access
SET search_path TO ops;


-- =========================================================
-- Inspect Orders Table
-- =========================================================

SELECT * FROM orders;


-- =========================================================
-- Check for NULL values in Orders table
-- Ensures critical fields required for analysis are present
-- =========================================================

SELECT
SUM(CASE WHEN order_date IS NULL THEN 1 ELSE 0 END) AS order_null,
SUM(CASE WHEN customer_country IS NULL THEN 1 ELSE 0 END) AS country_null,
SUM(CASE WHEN destination_country IS NULL THEN 1 ELSE 0 END) AS destination_null,
SUM(CASE WHEN hub_id IS NULL THEN 1 ELSE 0 END) AS hub_null,
SUM(CASE WHEN product_category IS NULL THEN 1 ELSE 0 END) AS category_null,
SUM(CASE WHEN order_value IS NULL THEN 1 ELSE 0 END) AS value_null,
SUM(CASE WHEN priority_flag IS NULL THEN 1 ELSE 0 END) AS flag_null,
SUM(CASE WHEN promised_delivery_date IS NULL THEN 1 ELSE 0 END) AS delivery_null
FROM orders;


-- =========================================================
-- Check missing values in fulfilment events
-- stage_end_time is critical for duration and SLA analysis
-- =========================================================

SELECT
SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS order_null,
SUM(CASE WHEN stage_name IS NULL THEN 1 ELSE 0 END) AS stage_null,
SUM(CASE WHEN stage_start_time IS NULL THEN 1 ELSE 0 END) AS start_time_null,
SUM(CASE WHEN stage_end_time IS NULL THEN 1 ELSE 0 END) AS end_time_null,
SUM(CASE WHEN status IS NULL THEN 1 ELSE 0 END) AS status_null,
SUM(CASE WHEN hub_id IS NULL THEN 1 ELSE 0 END) AS hub_null
FROM fulfilment_events;


-- Inspect rows with missing stage_end_time
SELECT *
FROM fulfilment_events
WHERE stage_end_time IS NULL;


-- =========================================================
-- Detect duplicate stage events
-- Each order should ideally have only one entry per stage
-- =========================================================

SELECT order_id, stage_name, COUNT(*)
FROM ops.fulfilment_events
GROUP BY order_id, stage_name
HAVING COUNT(*) > 1;


-- =========================================================
-- NOTE:
-- During early data loading some improper tables were created
-- and the schema had to be recreated before loading the data again
-- =========================================================

-- DROP TABLE ops.fulfilment_events;
-- DROP SCHEMA ops CASCADE;
-- CREATE SCHEMA ops;


-- Preview dataset loaded via Python
SELECT *
FROM ops2.fulfilment_events;


-- =========================================================
-- Identify records with missing stage_end_time
-- These rows will be excluded from SLA duration calculations
-- =========================================================

SELECT *
FROM fulfilment_events
WHERE stage_end_time IS NULL;


-- =========================================================
-- Detect negative stage durations
-- Indicates incorrect timestamps in event logs
-- =========================================================

SELECT *
FROM fulfilment_events
WHERE stage_end_time < stage_start_time;


-- =========================================================
-- Check again for duplicate stage records
-- =========================================================

SELECT order_id, stage_name, COUNT(*)
FROM fulfilment_events
GROUP BY order_id, stage_name
HAVING COUNT(*) > 1;


-- =========================================================
-- Identify orders missing Delivery stage
-- Indicates incomplete fulfilment pipeline
-- =========================================================

SELECT *
FROM orders o
LEFT JOIN fulfilment_events f
ON o.order_id = f.order_id
AND f.stage_name = 'Delivery'
WHERE f.order_id IS NULL;


-- =========================================================
-- Detect orphan records
-- Records in child tables without matching parent orders
-- =========================================================

-- Shipping records without matching order
SELECT sc.order_id
FROM shipping sc
LEFT JOIN orders o
ON sc.order_id = o.order_id
WHERE o.order_id IS NULL;


-- Returns recorded without corresponding delivery stage
SELECT r.order_id
FROM returns r
LEFT JOIN ops.fulfilment_events f
ON r.order_id = f.order_id
WHERE f.order_id IS NULL;


-- =========================================================
-- Detect unrealistic operational load
-- Identify days where orders exceed 150% of hub capacity
-- =========================================================

WITH daily_volume AS (
    SELECT hub_id, DATE(order_date) AS day, COUNT(*) AS orders
    FROM orders
    GROUP BY hub_id, DATE(order_date)
)

SELECT h.hub_name, day, orders, h.capacity_per_day
FROM daily_volume d
JOIN hubs h ON d.hub_id = h.hub_id
WHERE orders > h.capacity_per_day * 1.5;


-- =========================================================
-- Investigate patterns in missing stage_end_time values
-- =========================================================

SELECT status,
COUNT(*) AS missing_end_times
FROM ops.fulfilment_events
WHERE stage_end_time IS NULL
GROUP BY 1;


-- Inspect problematic cases such as "Rework"
SELECT *
FROM ops.fulfilment_events
WHERE status = 'Rework';

-- =========================================================
-- Handling Missing Stage End Times & Event Cleaning
-- This section fixes missing timestamps and creates a clean
-- operational events table for SLA and duration analysis.
-- =========================================================


-- =========================================================
-- Create a view to handle missing stage_end_time values
-- Strategy:
-- If stage_end_time is NULL, use the start time of the next stage
-- =========================================================

CREATE VIEW null_events_handled AS
WITH ordered_events AS (
    SELECT
        order_id,
        stage_name,
        stage_start_time,
        stage_end_time,
        status,
        hub_id,
        LEAD(stage_start_time) OVER (
            PARTITION BY order_id
            ORDER BY stage_start_time
        ) AS next_stage_start_time      -- next stage start time per order
    FROM fulfilment_events
)

SELECT
    order_id,
    stage_name,
    stage_start_time,
    CASE
        WHEN stage_end_time IS NOT NULL THEN stage_end_time
        WHEN stage_end_time IS NULL
             AND next_stage_start_time IS NOT NULL
        THEN next_stage_start_time      -- impute missing end time
        ELSE NULL
    END AS adjusted_stage_end_time,
    status,
    hub_id
FROM ordered_events;


-- =========================================================
-- Validate that missing end times were handled correctly
-- =========================================================

SELECT *
FROM null_events_handled
WHERE adjusted_stage_end_time IS NULL;


-- Check for invalid negative durations
SELECT *
FROM null_events_handled
WHERE adjusted_stage_end_time < stage_start_time;


-- =========================================================
-- Create a materialized view for cleaned fulfilment events
-- Materialized view improves performance for repeated analysis
-- =========================================================

CREATE MATERIALIZED VIEW fulfilment_events_clean AS
WITH ordered_events AS (
    SELECT
        order_id,
        stage_name,
        stage_start_time,
        stage_end_time,
        status,
        hub_id,
        LEAD(stage_start_time) OVER (
            PARTITION BY order_id
            ORDER BY stage_start_time
        ) AS next_stage_start_time
    FROM fulfilment_events
)

SELECT
    order_id,
    stage_name,
    stage_start_time,
    CASE
        WHEN stage_end_time IS NOT NULL THEN stage_end_time
        WHEN stage_end_time IS NULL
             AND next_stage_start_time IS NOT NULL
        THEN next_stage_start_time
        ELSE NULL
    END AS adjusted_stage_end_time,
    status,
    hub_id
FROM ordered_events;


-- Refresh materialized view after new data loads
REFRESH MATERIALIZED VIEW fulfilment_events_clean;


-- Inspect shipping table
SELECT * FROM shipping;


-- =========================================================
-- Stage Sequence Validation
-- Ensure fulfilment stages follow expected pipeline order
-- Intake → QC → Packing → Shipping → Delivery
-- =========================================================

WITH ordered AS (
    SELECT
        order_id,
        stage_name,
        stage_start_time,
        LAG(stage_name) OVER (
            PARTITION BY order_id
            ORDER BY stage_start_time
        ) AS previous_stage
    FROM fulfilment_events
)

SELECT *
FROM ordered
WHERE previous_stage = 'Packing'
AND stage_name <> 'Shipping';


-- =========================================================
-- Identify Orders Without Complete Stage Coverage
-- Each order should ideally have all 5 fulfilment stages
-- =========================================================

SELECT order_id
FROM ops.fulfilment_events
GROUP BY order_id
HAVING COUNT(DISTINCT stage_name) < 5;


-- =========================================================
-- Detect Unrealistic Stage Durations
-- Flag durations exceeding operational thresholds
-- =========================================================

SELECT *
FROM fulfilment_events_clean
WHERE EXTRACT(EPOCH FROM (adjusted_stage_end_time - stage_start_time))/3600 > 200;


-- =========================================================
-- Detect Overlapping Stages (Operational Data Issue)
-- =========================================================

WITH ordered AS (
    SELECT *,
        LAG(adjusted_stage_end_time) OVER (
            PARTITION BY order_id
            ORDER BY stage_start_time
        ) AS previous_end
    FROM fulfilment_events_clean
)

SELECT *
FROM ordered
WHERE stage_start_time < previous_end;


-- =========================================================
-- Validate that orders do not have multiple delivery stages
-- =========================================================

SELECT order_id, COUNT(*)
FROM fulfilment_events_clean
WHERE stage_name = 'Delivery'
GROUP BY order_id
HAVING COUNT(*) > 1;


-- =========================================================
-- Prepare Data for SLA & Turnaround Time (TAT) Analysis
-- Only include completed delivery events
-- =========================================================

SELECT * FROM ops.orders;
SELECT * FROM ops.fulfilment_events_clean;


-- Join orders with cleaned fulfilment events
SELECT *
FROM ops.orders o
LEFT JOIN ops.fulfilment_events_clean f
ON o.order_id = f.order_id;


-- =========================================================
-- Create view for eligible orders used in TAT analysis
-- Conditions:
-- 1. Delivery stage must exist
-- 2. adjusted_stage_end_time must not be NULL
-- =========================================================

CREATE VIEW TAT AS
SELECT
    o.order_id,
    o.order_date,
    MAX(f.adjusted_stage_end_time) AS delivery_time,  -- safeguard against duplicate delivery records
    o.hub_id,
    o.priority_flag,
    o.promised_delivery_date
FROM orders o
JOIN fulfilment_events_clean f
    ON o.order_id = f.order_id
WHERE f.stage_name = 'Delivery'
AND f.adjusted_stage_end_time IS NOT NULL
GROUP BY
    o.order_id,
    o.order_date,
    o.hub_id,
    o.priority_flag,
    o.promised_delivery_date;

-- =========================================================
-- KPI Analysis (Operational Performance Metrics)
-- This section answers key business questions related to
-- fulfilment efficiency, SLA adherence, and hub performance.
-- =========================================================


-- =========================================================
-- Q1. Stage-wise average processing time
-- Measures average duration spent in each fulfilment stage
-- =========================================================

SELECT stage_name,
ROUND(AVG(EXTRACT(EPOCH FROM (adjusted_stage_end_time - stage_start_time))/3600),2) || ' Hrs'
AS avg_stage_hours
FROM fulfilment_events_clean
WHERE adjusted_stage_end_time IS NOT NULL
GROUP BY stage_name
ORDER BY avg_stage_hours DESC;



-- =========================================================
-- Q2. Overall average Turnaround Time (Order → Delivery)
-- Measures total time from order placement to final delivery
-- =========================================================

SELECT
ROUND(AVG(EXTRACT(EPOCH FROM (delivery_time - order_date))/3600),2) || ' Hrs'
AS avg_tat_hours
FROM TAT;



-- Alternative calculation directly from base tables

WITH delivered_orders AS (
    SELECT
        o.order_id,
        o.order_date,
        MAX(f.adjusted_stage_end_time) AS delivery_time
    FROM orders o
    JOIN fulfilment_events_clean f
        ON o.order_id = f.order_id
    WHERE f.stage_name = 'Delivery'
      AND f.adjusted_stage_end_time IS NOT NULL
    GROUP BY o.order_id, o.order_date
)

SELECT
ROUND(
AVG(EXTRACT(EPOCH FROM (delivery_time - order_date))/3600),
2) AS avg_tat_hours
FROM delivered_orders;



-- =========================================================
-- Q3. Which hub has the highest TAT variance?
-- Helps identify operational instability across hubs
-- =========================================================
	WITH delivered_orders AS (
	    SELECT
	        o.order_id,
	        o.hub_id,
	        o.order_date,
	        MAX(f.adjusted_stage_end_time) AS delivery_time
	    FROM orders o
	    JOIN fulfilment_events_clean f
	        ON o.order_id = f.order_id
	    WHERE f.stage_name = 'Delivery'
	      AND f.adjusted_stage_end_time IS NOT NULL
	    GROUP BY o.order_id, o.hub_id, o.order_date
	),
	
	tat_per_order AS (
	    SELECT
	        order_id,
	        hub_id,
	        EXTRACT(EPOCH FROM (delivery_time - order_date)) / 86400 AS tat_days
	    FROM delivered_orders
	)
	
	SELECT
	    h.hub_name,
	    ROUND(AVG(t.tat_days), 2) AS avg_tat_days,
	    ROUND(VAR_SAMP(t.tat_days), 2) AS tat_variance_days
	FROM tat_per_order t
	JOIN hubs h ON t.hub_id = h.hub_id
	GROUP BY h.hub_name
	ORDER BY tat_variance_days DESC;
	;



-- =========================================================
-- Q4. Which stage contributes most to SLA breaches?
-- Calculates stage-level SLA violations
-- =========================================================

	WITH stage_durations AS (
	    SELECT
	        f.stage_name,
	        EXTRACT(EPOCH FROM 
	            (f.adjusted_stage_end_time - f.stage_start_time)
	        ) / 3600 AS stage_hours,
	        s.sla_hours
	    FROM fulfilment_events_clean f
	    JOIN sla s
	        ON f.stage_name = s.stage_name
	    WHERE f.adjusted_stage_end_time IS NOT NULL
	),
	
	breach_flags AS (
	    SELECT
	        stage_name,
	        CASE 
	            WHEN stage_hours > sla_hours THEN 1
	            ELSE 0
	        END AS breach_flag
	    FROM stage_durations
	)
	
	SELECT
	    stage_name,
	    SUM(breach_flag) AS total_breaches,
	    ROUND(
	        SUM(breach_flag) * 100.0 / 
	        SUM(SUM(breach_flag)) OVER (), 2
	    ) AS contribution_percentage
	FROM breach_flags
	GROUP BY stage_name
	ORDER BY total_breaches DESC;;



-- =========================================================
-- Q5. What % of orders breach Delivery SLA?
-- =========================================================

	With cte as (
	Select 
	order_id,
	f.stage_name,
	ROUND(EXTRACT(EPOCH from(adjusted_stage_end_time - stage_start_time))/3600,2) as hour_diff,
	s.sla_hours
	From ops.fulfilment_events_clean f
	JOIN sla s
	ON f.stage_name = s.stage_name
	WHERE f.adjusted_stage_end_time IS NOT NULL
	AND s.stage_name = 'Delivery')
	
	Select
	stage_name,
	SUM(CASE WHEN hour_diff > sla_hours Then 1 Else 0 ENd) as sla_breach,
	COUNT(*) as total_delivered_orders,
	CONCAT(ROUND(100* SUM(CASE WHEN hour_diff > sla_hours Then 1 Else 0 ENd) / 
	COUNT(*),2),'%') as breach_pct
	From cte
	Group by 1;



-- =========================================================
-- Q6. What % of orders breach any stage SLA?
-- =========================================================

	-- Meaning kitne percent orders mai atleast 1 SLA breach hua hai 
	
	With cte as (
	Select 
	order_id,
	f.stage_name,
	ROUND(EXTRACT(EPOCH from(adjusted_stage_end_time - stage_start_time))/3600,2) as hour_diff,
	s.sla_hours
	From ops.fulfilment_events_clean f
	JOIN sla s
	ON f.stage_name = s.stage_name
	WHERE f.adjusted_stage_end_time IS NOT NULL
	)
	
	Select
	ROUND(100* COUNT(CASE WHEN sla_breach != 0 Then 1 END)/COUNT(order_id),2) as sla_breach
	from(
	Select
	order_id,
	SUM(CASE WHEN hour_diff > sla_hours Then 1 Else 0 ENd) as sla_breach,
	COUNT(*) as total_stages
	--CONCAT(ROUND(100* SUM(CASE WHEN hour_diff > sla_hours Then 1 Else 0 ENd) / COUNT(*),2),'%') as breach_pct
	From cte
	Group by 1)as s;
	


-- =========================================================
-- Q7. SLA breach rate by hub
-- =========================================================

	with cte As (
	Select 
	order_id,
	-- f.stage_name,
	f.hub_id, h.hub_name,
	ROUND(EXTRACT(EPOCH from(adjusted_stage_end_time - stage_start_time))/3600,2) as hour_diff,
	s.sla_hours
	From ops.fulfilment_events_clean f
	JOIN sla s
	ON f.stage_name = s.stage_name
	Join hubs h
	ON h.hub_id = f.hub_id
	WHERE f.adjusted_stage_end_time IS NOT NULL )
	
	Select
	hub_name,
	SUM(CASE WHEN hour_diff > sla_hours Then 1 END) as sla_breach,
	COUNT(*) as total_hub_orders,
	ROUND(100* COUNT(CASE WHEN hour_diff > sla_hours Then 1 END) / COUNT(*),2) as breach_rate
	From cte
	Group by 1;


-- =========================================================
-- Q8. SLA breach trend month-over-month
-- =========================================================

	Select * From ops.fulfilment_events_clean;
	with cte As (
	Select 
	order_id,
	EXTRACT(Month From(adjusted_stage_end_time)) as breach_month_num,
	To_Char(adjusted_stage_end_time,'Mon') as month_text,
	adjusted_stage_end_time,
	ROUND(EXTRACT(EPOCH from(adjusted_stage_end_time - stage_start_time))/3600,2) as hour_diff,
	s.sla_hours
	From ops.fulfilment_events_clean f
	JOIN sla s
	ON f.stage_name = s.stage_name
	WHERE f.adjusted_stage_end_time IS NOT NULL ),
	
	cte1 AS (
	Select
	breach_month_num, month_text,
	SUM(CASE WHEN hour_diff > sla_hours Then 1 END) as sla_breach,
	COUNT(*) as total_month_orders,
	ROUND(100* COUNT(CASE WHEN hour_diff > sla_hours Then 1 END) / COUNT(*),2) as breach_rate
	From cte
	Group by 1,2
	ORDER BY 1,2)
	
	
	Select
	breach_month_num, month_text, sla_breach,
	COALESCE(LAG(sla_breach) over (order by breach_month_num),0) as prev_sla_breach,
	COALESCE(ROUND(100.0 * (LAG(sla_breach) over (order by breach_month_num) - sla_breach) / NULLIF(LAG(sla_breach) OVER (ORDER BY breach_month_num),0),2),0) as breach_Mom
	from cte1; monthly_stats;



-- =========================================================
-- Q9. Express vs Standard SLA comparison
-- =========================================================

	with cte as(
	Select
	priority_flag,
	f.order_id,
	f.stage_name,
	ROUND(EXtract(Epoch From(adjusted_stage_end_time - stage_start_time))/3600,2) as diff_hrs,
	sla_hours
	From orders o
	JOIN ops.fulfilment_events_clean f
	ON o.order_id = f.order_id
	JOIN sla s
	ON f.stage_name = s.stage_name
	Where f.stage_name = 'Delivery'
	AND adjusted_stage_end_time is not NULL
	Order by o.order_id)
	
	
	Select
	DISTINCT priority_flag,
	SUM(CASE WHEN diff_hrs > sla_hours Then 1 ELse 0 ENd) as sla_breach,
	COUNT(*) as total_stages,
	ROUND(100.0 * SUM(CASE WHEN diff_hrs > sla_hours Then 1 ELse 0 ENd)/COUNT(*),2) as pct
	from cte
	Group by 1;



-- =========================================================
-- Q10. What % of SLA breaches originate in QC stage?
-- =========================================================

	with cte as(
	Select
	f.order_id,
	f.stage_name,
	ROUND(EXtract(Epoch From(adjusted_stage_end_time - stage_start_time))/3600,2) as diff_hrs,
	sla_hours
	From orders o
	JOIN ops.fulfilment_events_clean f
	ON o.order_id = f.order_id
	JOIN sla s
	ON f.stage_name = s.stage_name
	AND adjusted_stage_end_time is not NULL
	Order by o.order_id)
	
	
	Select
	
	SUM(CASE WHEN stage_name = 'QC' AND diff_hrs > sla_hours Then 1 ELse 0 ENd) as sla_qc_breach,
	SUM(CASE WHEN diff_hrs > sla_hours Then 1 ELse 0 ENd) as total_breaches,
	ROUND(100.0 * SUM(CASE WHEN stage_name = 'QC' AND diff_hrs > sla_hours Then 1 ELse 0 ENd) /
	SUM(CASE WHEN diff_hrs > sla_hours Then 1 ELse 0 ENd),2) as pct
	from cte;



-- =========================================================
" B. Bottlenecks & Flow Efficiency (11–20)
	-- Q11.	Average queue time between stages? "
  -- =========================================================
  
	Select * from ops.fulfilment_events_clean;
	
	With cte as (
	Select *, LAG(adjusted_stage_end_time)  oVER (partition by order_id Order by stage_start_time) as previous_time
	from ops.fulfilment_events_clean)
	
	Select stage_name,
	ROUND(AVG(EXTRACT(EPOCH FROM (stage_start_time - previous_time))/3600),2) as avg_queue_time
	From cte
	-- WHere previous_time is Not NULL
	WHere stage_start_time >= previous_time
	Group by 1;



-- =========================================================
	-- Q12.	Which stage has highest processing time variability?
	-- =========================================================

	Select
	stage_name,
	ROUND(AVG(processing_time),2) as avg_stage_hours,
	ROUND(STDDEV(processing_time), 2) AS stddev_stage_hours,
	ROUND(VAR_SAMP(processing_time), 2) AS variance_stage_hours
	FROM (
	    SELECT
	        stage_name,
	        hub_id,
	        ROUND(
	            EXTRACT(EPOCH FROM (adjusted_stage_end_time - stage_start_time)) / 3600,
	            2
	        ) AS processing_time
	    FROM ops.fulfilment_events_clean
	    WHERE adjusted_stage_end_time IS NOT NULL
	) AS n
	Group by 1;
	"
	Select
	*
	
	FROM (
	    SELECT
	        stage_name,
	        hub_id,
	        ROUND(
	            EXTRACT(EPOCH FROM (adjusted_stage_end_time - stage_start_time)) / 3600,
	            2
	        ) AS processing_time
	    FROM ops.fulfilment_events_clean
	    WHERE adjusted_stage_end_time IS NOT NULL
	) AS n
	JOIN hubs h
	ON n.hub_id = h.hub_id;
	just for reference "



  -- =========================================================
	-- Q13.	QC rework rate by hub?
	-- =========================================================
    
	Select hub_name,
	SUM(CASE WHEN status = 'Rework' Then 1 Else 0 End) as  qc_rework,
	COUNT(*) as total_orders,
	ROUND(100.0 * SUM(CASE WHEN status = 'Rework' Then 1 Else 0 End) / COUNT(*),2) as rework_rate
	from ops.fulfilment_events_clean f
	Join hubs h
	ON h.hub_id = f.hub_id
	Where stage_name = 'QC'
	and adjusted_stage_end_time is not null
	Group BY 1;
	


-- =========================================================
	-- Q14.	Does QC rework increase overall TAT?
-- =========================================================

	Select * From ops.fulfilment_events_clean;
	Select *
	Where stage_name = 'QC'
	and adjusted_stage_end_time is not null;
	
	-- Calculating overall TAT which is (delivery time - order time)
	
	With cte as (
	Select o.order_id,
	order_date,
	MAX(adjusted_stage_end_time) as delivery_date -- to avoid any dupicate order_id
	From orders o
	JOIN ops.fulfilment_events_clean f
	ON o.order_id = f.order_id
	Where stage_name = 'Delivery'
	AND adjusted_stage_end_time is not null
	Group by 1,2),
	
	-- caculate tat on order level
	order_level_tat as (
	Select
	order_id,
	EXTRACT(EPOCH From(delivery_date - order_date))/86400 as tat_days
	from cte
	order by 1),
	
	order_level_rework_flag as (
	Select 
	order_id,
	MAX(CASE When status = 'Rework' Then 1 Else 0 End) as rework_flag -- Max used to avoid duplicates
	From ops.fulfilment_events_clean
	Where stage_name = 'QC'
	AND adjusted_stage_end_time is not null
	Group by 1)
	
	SELECT
	    q.rework_flag,
	    COUNT(*) AS total_orders,
	    ROUND(AVG(t.tat_days), 2) AS avg_tat_days
	FROM order_level_tat t
	JOIN order_level_rework_flag q
	    ON t.order_id = q.order_id
	GROUP BY 1
	ORDER BY 1 DESC;
	


-- =========================================================
	-- Q15.	Backlog volume per hub (orders open > SLA)?
	-- Orders that are still open AND already beyond SLA threshold.
-- =========================================================

	Select * from orders;
	Select * from ops.fulfilment_events_clean;
	
	-- first find out orders that are not delivered
	with cte as (
	Select Distinct  order_id, order_date, hub_id,
	ROUND(EXTRACT (EPOCH From (NOW() - order_date)) / 3600,2) as elapsed_hours
	From orders
	Where order_id NOT IN 
	(
	Select
	distinct order_id
	From ops.fulfilment_events_clean 
	Where stage_name = 'Delivery'  -- inner query we find the delivered orders and then substract it in outer query
	ANd  adjusted_stage_end_time is not null)
	ORDER BY 1),
	
	cte1 as (
	Select sla_hours
	From sla
	Where stage_name = 'Delivery')
	
	Select hub_name,
	SUM(CASE WHEN elapsed_hours > sla_hours then 1 else 0 end) as backlog
	From cte c
	JOIN hubs h
	on c.hub_id = h.hub_id
	cross join cte1 c1
	Group by 1
	;
	
	-- Not exits syntax for the above query 
	
	SELECT DISTINCT  
	    o.order_id, 
	    o.order_date, 
	    o.hub_id,
	    ROUND(
	        EXTRACT(EPOCH FROM (NOW() - o.order_date)) / 3600,
	        2
	    ) AS elapsed_hours
	FROM orders o
	WHERE NOT EXISTS (
	    SELECT 1
	    FROM ops.fulfilment_events_clean f
	    WHERE f.order_id = o.order_id
	      AND f.stage_name = 'Delivery'
	      AND f.adjusted_stage_end_time IS NOT NULL
	)
	ORDER BY o.order_id;



-- =========================================================
	-- Q16.	Daily throughput per hub?
-- =========================================================

	select * from orders;
	Select * from ops.fulfilment_events_clean;
	
	Select hub_name,
	DATE(adjusted_stage_end_time) as processing_date,
	COUNT(*) as orders_processed
	from ops.fulfilment_events_clean f
	join hubs h 
	on h.hub_id = f.hub_id
	Where f.stage_name = 'Delivery'
	AND adjusted_stage_end_time is not Null
	Group by 1,2
	Order by 1,2;



-- =========================================================
	-- Q17.	Hub capacity utilisation %?
-- =========================================================

	select * From ops.hubs;
	
	WIth cte as (
	Select hub_id,
	DATE(adjusted_stage_end_time) as delivered_date,
	COUNT(*) as orders
	from ops.fulfilment_events_clean f
	Where f.stage_name = 'Delivery'
	AND adjusted_stage_end_time is not Null
	Group by 1,2
	Order by 1,2)
	
	Select
	hub_name,
	delivered_date,
	ROUND(100.0 * orders / capacity_per_day,2) as utilization_ratio
	From cte c
	JOIN hubs h
	ON c.hub_id = h.hub_id
	;



-- =========================================================
	-- Q18.	Are there days exceeding 110% capacity?
-- =========================================================

	WIth cte as (
	Select hub_id,
	DATE(adjusted_stage_end_time) as delivered_date,
	COUNT(*) as orders
	from ops.fulfilment_events_clean f
	Where f.stage_name = 'Delivery'
	AND adjusted_stage_end_time is not Null
	Group by 1,2
	Order by 1,2)
	
	
	Select
	*
	From(
	Select
	hub_name,
	delivered_date,
	ROUND(100.0 * orders / capacity_per_day,2) as utilization_ratio
	From cte c
	JOIN hubs h
	ON c.hub_id = h.hub_id
	)
	Where utilization_ratio > 110;



-- =========================================================
	-- Q19.	What happens to SLA breach rate on high-utilisation days?
-- =========================================================

	WIth cte as (
	Select f.hub_id,
	DATE(adjusted_stage_end_time) as delivered_date,
	capacity_per_day,
	COUNT(*) as orders,
	ROUND(100.0 * COUNT(*) / capacity_per_day,2) as utilization_ratio
	from ops.fulfilment_events_clean f
	join hubs h
	on f.hub_id = h.hub_id
	Where f.stage_name = 'Delivery'
	AND adjusted_stage_end_time is not Null
	Group by 1,2,3
	Order by 1,2,3),
	
	utilzation_tag as ( -- this shows a hub is over or normally utilized
	Select
	*,
	CASE when utilization_ratio > 110 Then 'Over Utilized' Else 'Normal Utilized' End as utilized_type
	From cte
	),
	
	delivery_breaches as ( -- order wise sla_breach pata karege for every hubs 
	SELECT 
	o.hub_id,
	o.order_id,
	order_date,
	DATE(adjusted_stage_end_time) as delivery_time,
	ROUND(EXTRACT (EPOCH From(adjusted_stage_end_time - order_date))/3600,2) as process_hrs,
	sla_hours
	From orders o 
	JOIN ops.fulfilment_events_clean f
	ON o.order_id = f.order_id
	JOIN sla s
	on s.stage_name = f.stage_name
	Where f.stage_name = 'Delivery'
	AND adjusted_stage_end_time is not Null
	)
	
	Select
	utilized_type,
	SUM(CASE WHEN process_hrs > sla_hours Then 1 Else 0 End) as sla_breaces,
	COUNT(*) as total_orders,
	ROUND(100.0 * SUM(CASE WHEN process_hrs > sla_hours Then 1 Else 0 End) / COUNT(*),2) as sla_breach_rate
	from utilzation_tag u
	JOIN delivery_breaches d
	ON u.hub_id = d.hub_id
	AND u.delivered_date = d.delivery_time
	Group by 1;
	


-- =========================================================
	-- Q20.	Which hub is most operationally unstable?
-- =========================================================

	'What Does Operationally Unstable Mean?
	
	Possible interpretations:
	
	1️⃣ High TAT variability
	2️⃣ High SLA breach variability
	3️⃣ High throughput volatility
	4️⃣ High queue time fluctuation
	5️⃣ High utilisation volatility '
	
	-- we would consider HIGH TAT Variability
	With cte as (
	Select
	f.hub_id,
	f.order_id,
	 EXTRACT(EPOCH FROM 
	            (f.adjusted_stage_end_time - o.order_date)
	        ) / 86400 AS tat_days
	 FROM orders o
	    JOIN ops.fulfilment_events_clean f
	        ON o.order_id = f.order_id
	    WHERE f.stage_name = 'Delivery'
	      AND f.adjusted_stage_end_time IS NOT NULL)
		  
	Select
	hub_name,
	ROUND(AVG(tat_days), 2) AS avg_tat_days,
	ROUND(STDDEV(tat_days), 2) AS tat_stddev_days,
	ROUND(VAR_SAMP(tat_days),2) as tat_var_days,
	ROUND(
	        STDDEV(tat_days) / NULLIF(AVG(tat_days), 0),
	        2
	    ) AS coeff_variation
	from cte c
	JOIN hubs h
	on c.hub_id = h.hub_id
	Group by 1;



-- =========================================================
-- 🔹 C. Shipping & Cost Efficiency (21–30)
	-- Q21.	Average shipping cost per order?
-- =========================================================

	Select * from shipping;
	Select * from orders;
	Select * from ops.fulfilment_events_clean;
	
	WIth cte as (
	Select order_id,
	SUM(shipping_cost) as shipping_cost
	from shipping  -- we are doing this just in case there are multiple shipping costs invloved per order
	Group by 1)
	
	Select 
	ROUND(AVG(shipping_cost),2) as avg_ship_cost_per_order
	From cte;



-- =========================================================
	-- Q22.	Shipping cost by zone?
-- =========================================================

	Select shipping_zone,
	ROUND(AVG(shipping_cost),2) as shipping_cost
	from shipping  -- we are doing this just in case there are multiple shipping costs invloved per order
	Group by 1;



-- =========================================================
	-- Q23.	Shipping cost by weight bucket?
-- =========================================================

	Select weight_bucket,
	ROUND(AVG(shipping_cost),2) as shipping_cost
	from shipping  -- we are doing this just in case there are multiple shipping costs invloved per order
	Group by 1;



-- =========================================================
	-- Q24.	Which shipping partner has best on-time rate?
-- =========================================================

	with cte as (
	Select o.order_id,
	order_date,
	promised_Delivery_date,
	DATE(adjusted_stage_end_time) as actual_delivery_date,
	shipping_partner
	From orders o
	JOIN ops.fulfilment_events_clean f
	on o.order_id = f.order_id
	JOIN shipping s
	ON s.order_Id = o.order_id
	Where stage_name = 'Delivery'
	AND adjusted_stage_end_time is not null)
	
	Select 
	shipping_partner,
	SUM(CASE WHEN actual_delivery_date <= promised_delivery_date then 1 else 0 end) as on_time_delivery,
	COUNT(Distinct order_id) as total_orders,
	ROUND(100.0 * SUM(CASE WHEN actual_delivery_date <= promised_delivery_date then 1 else 0 end) / COUNT(*),2) || '%' as on_time_rate
	-- SUM(COUNT(*)) over (partition by shipping_partner) as total_orders
	From cte
	Group by 1;
	


-- =========================================================
	-- Q25.	Which partner has lowest cost?
-- =========================================================

	Select * from shipping;
	with cte as (
	Select
	shipping_partner,
	ROUND(AVG(shipping_cost)) as avg_ship_cost
	From shipping
	Group by 1)
	
	Select
	shipping_partner,
	avg_ship_cost
	From (
	Select
	*,
	Dense_rank() over (order by avg_ship_cost) as rnk
	From cte ) a
	Where rnk = 1;
	
	-- Method 2
	Select
	shipping_partner,
	ROUND(AVG(shipping_cost)) as avg_ship_cost
	From shipping
	Group by 1
	Order by 2
	Limit 1;
	


-- =========================================================
-- Q26.	Cost per on-time delivery? 
-- =========================================================

	' total shipping cost / Number of on-time deliveries'
    
	Select * from shipping;
	Select * from ops.fulfilment_events_clean;
	
	with cte as (
	Select o.order_id,
	order_date,
	promised_Delivery_date,
	DATE(adjusted_stage_end_time) as actual_delivery_date,
	shipping_partner,
	shipping_cost
	From orders o
	JOIN ops.fulfilment_events_clean f
	on o.order_id = f.order_id
	JOIN shipping s
	ON s.order_Id = o.order_id
	Where stage_name = 'Delivery'
	AND adjusted_stage_end_time is not null)
	
	Select 
	shipping_partner,
	COUNT(CASE WHEN actual_delivery_date <= promised_delivery_date THEN 1 END) AS on_time_orders,
	ROUND(
	        SUM(shipping_cost) /
	        NULLIF(
	            COUNT(CASE 
	                WHEN actual_delivery_date <= promised_delivery_date 
	                THEN 1 
	            END),0
	        ),2) AS cost_per_on_time_delivery
	-- SUM(COUNT(*)) over (partition by shipping_partner) as total_orders
	From cte
	Group by 1;



-- =========================================================
	-- Q27.	Does higher shipping cost reduce SLA breach?
-- =========================================================

	Select * from sla;
	Select * from shipping;
	Select *
	Select MAX(shipping_cost), Min(shipping_cost) from shipping;
	
	WIth cte as (
	Select o.order_id,
	-- order_date,
	promised_Delivery_date,
	DATE(adjusted_stage_end_time) as actual_delivery_date,
	shipping_partner,
	shipping_cost,
	Case When DATE(adjusted_stage_end_time) > promised_delivery_date then 1 Else 0 End as breach_flag,
	CASE 
	 WHEN shipping_cost > 100 then 'High Cost'
	 When shipping_cost between 60 and 100 then 'Medium Cost'
	 Else 'Low Cost' End as cost_bracket
	From orders o
	JOIN ops.fulfilment_events_clean f
	on o.order_id = f.order_id
	JOIN shipping s
	ON s.order_Id = o.order_id
	Where stage_name = 'Delivery'
	AND adjusted_stage_end_time is not null)
	
	Select 
	cost_bracket,
	SUM(breach_flag) as sla_breaches,
	SUM(SUM(breach_flag)) OVER () as total_breaches,
	ROUND(100.0 * SUM(breach_flag) / SUM(SUM(breach_flag)) OVER () ,2) as breach_rate
	from cte 
	Group by 1;



-- =========================================================
	-- Q28.	Shipping cost as % of order value?
-- =========================================================

	Select * from shipping;
	Select * from orders;
	Select * from ops.fulfilment_events_clean;
	
	Select shipping_partner,
	ROUND(100.0* SUM(shipping_cost) / sum(order_value),2) as ship_cost_pct_order
	From orders o
	Join shipping s
	ON o.order_id = s.order_id
	Group by 1;
	
	Select shipping_partner,
	ROUND(100.0* AVG(shipping_cost)/AVG(order_value),2) as ship_cost_pct_order
	From orders o
	Join shipping s
	ON o.order_id = s.order_id
	Group by 1;
	
	-- this one gives the actual metric because it is done on order level first then the avg is calculated
	Select shipping_partner,
	ROUND(100.0* AVG(shipping_cost/order_value),2) as ship_cost_pct_order
	From orders o
	Join shipping s
	ON o.order_id = s.order_id
	Group by 1;



-- =========================================================
-- Q29.	Express shipping cost vs incremental revenue?
-- =========================================================

WITH order_shipping AS (
SELECT
    o.order_id,
    o.order_value,
    o.priority_flag,
    s.shipping_cost
FROM orders o
JOIN shipping s
ON o.order_id = s.order_id
)

SELECT
priority_flag,
COUNT(*) as total_orders,
ROUND(AVG(order_value),2) as avg_order_value,
ROUND(AVG(shipping_cost),2) as avg_shipping_cost,
ROUND(AVG(order_value - shipping_cost),2) as avg_margin
FROM order_shipping
GROUP BY priority_flag;



-- =========================================================
-- Q30.	Which hub has worst cost-to-performance ratio?
-- =========================================================

'We want hubs that:

Spend more shipping cost

Deliver worse SLA performance 
cost_to_performance_ratio =
avg_shipping_cost / on_time_rate'

With cte as ( 
Select o.order_id, o.order_date, o.hub_id, 
h.hub_name, promised_delivery_date, 
DATE(adjusted_stage_end_time) as actual_delivery_date, 
CASE WHEN DATE(adjusted_stage_end_time) <= promised_delivery_date then 1 else 0 end as breach_flag, 
shipping_cost 
From orders o 
Join ops.fulfilment_events_clean f 
ON o.order_id = f.order_id 
JOin shipping s 
ON s.order_id = o.order_id 
Join hubs h on o.hub_id = h.hub_id 
Where stage_name = 'Delivery' 
And adjusted_stage_end_time is not null Order by 1) 

Select hub_name, 
ROUND(100.0 * avg_ship_cost / on_time_rate,2) as cost_to_performance_ratio 
From ( 
Select hub_name, 
ROUND(avg(shipping_cost),2) avg_ship_cost, 
SUM(breach_flag) as on_time_orders, 
COUNT(distinct order_id) as total_orders, 
ROUND(100.0 * SUM(breach_flag) / COUNT(distinct order_id),2) as on_time_rate 
from cte Group by 1) as a;

-- the bigger the cost_to_performance_ratio is the worst performing hub it is 

'“What does worst cost-to-performance hub mean?”
It indicates hubs that are both expensive and unreliable, making them priority 
candidates for operational improvement or logistics partner renegotiation.'



-- =========================================================
-- 🔹 D. Returns & Customer Impact (31–38)
-- Q31.	Overall return rate?
-- =========================================================

Select * from returns;
Select * from orders;

Select 
ROUND(100.0 * COUNT(DISTINCT order_id) / (SELECT COUNT(DISTINCT order_id) From orders),2) as overall_return_rate
From orders
Where EXISTS (
Select 1
From returns
Where returns.order_id = orders.order_id);

-- Simpler version
SELECT
ROUND(
100.0 * COUNT(DISTINCT r.order_id) /
(SELECT COUNT(DISTINCT order_id) FROM orders),
2
) AS overall_return_rate
FROM returns r;



-- =========================================================
-- Q32.	Return rate by hub?
-- =========================================================

Select * from returns;
Select * from orders;
Select * from hubs;

Select
hub_name,
COUNT(distinct r.order_id) as return_orders,
COUNT(Distinct o.order_id) as total_orders,
ROUND(100.0 * COUNT(distinct r.order_id) / COUNT(Distinct o.order_id),2) as return_rate
from orders o
left join returns r
ON o.order_id = r.order_id
JOIN hubs h
on h.hub_id = o.hub_id
Group by 1;



-- =========================================================
-- Q33.	Return rate by destination country?
-- =========================================================

Select * from orders;

Select
customer_country,
COUNT(distinct r.order_id) as return_orders,
COUNT(Distinct o.order_id) as total_orders,
ROUND(100.0 * COUNT(distinct r.order_id) / COUNT(Distinct o.order_id),2) as return_rate
from orders o
left join returns r
ON o.order_id = r.order_id
JOIN hubs h
on h.hub_id = o.hub_id
Group by 1;



-- =========================================================
-- Q34.	Return rate by delay bucket (On-time, 1–2 days late, 3+ late)?
-- =========================================================

with cte AS (
Select o.order_id as total_order,
promised_delivery_date,
DATE(adjusted_stage_end_time) as actual_delivery_date,
r.order_id as return_order,
Case 
 	When DATE(adjusted_stage_end_time) <= promised_delivery_date Then 'On-time'
	 When DATE(adjusted_stage_end_time) - promised_delivery_date <=2 THen '1-2 days late'
	 Else '3+ days late'
	 End as delay_bucket
from orders o
Join ops.fulfilment_events_clean f
on o.order_id = f.order_id
left join returns r
on r.order_id = o.order_id
WHere f.stage_name = 'Delivery'
And adjusted_stage_end_time is not null)

Select delay_bucket,
COUNT(DISTINCT return_order) as return_orders,
COUNT(distinct total_order) as total_orders,
ROUND(100.0 * COUNT(DISTINCT return_order) / COUNT(distinct total_order),2) as return_rate
From cte 
Group by 1;



-- =========================================================
-- Q35.	Are late deliveries increasing returns probability?
-- =========================================================

'So we need two groups:
On-time deliveries
Late deliveries

Then compute:
return_probability = returned_orders / total_orders'

with cte AS (
Select o.order_id as total_order,
promised_delivery_date,
DATE(adjusted_stage_end_time) as actual_delivery_date,
r.order_id as return_order,
Case 
 	When DATE(adjusted_stage_end_time) <= promised_delivery_date Then 'On-time deilvery'
	 Else 'late delivery'
	 End as deliver_staus
from orders o
Join ops.fulfilment_events_clean f
on o.order_id = f.order_id
left join returns r
on r.order_id = o.order_id
WHere f.stage_name = 'Delivery'
And adjusted_stage_end_time is not null)

Select deliver_staus,
COUNT(DISTINCT return_order) as return_orders,
COUNT(distinct total_order) as total_orders,
ROUND(100.0 * COUNT(DISTINCT return_order) / COUNT(distinct total_order),2) as return_rate
From cte 
Group by 1;



-- =========================================================
-- Q36.	Refund value trend over time?
-- =========================================================

Select * from orders;
Select * from returns;

With cte As (
Select TO_CHAR(return_request_date,'YYYY-IW') as week_num,
-- DATE_PART('week', return_request_date)
-- DATE_TRUNC('week', order_date) AS week_start   (Postgres weeks start Monday)
-- EXTRACT(WEEK FROM return_request_date) AS week_num
-- EXTRACT(ISOWEEK FROM order_date) follow Monday → Sunday
-- 'week' || EXTRACT(WEEK FROM order_date)::INT AS week_label
SUM(refund_amount) as week_total,
LAG(SUM(refund_amount)) OVER (Order BY TO_CHAR(return_request_date,'YYYY-IW')) as previous_week_total
from returns
Group by 1
Order by 1)

Select
*,
ROUND(100.0* (week_total - previous_week_total) / previous_week_total,2) as wow
From cte;



-- =========================================================
-- Q37.	What % of refunds linked to SLA breach?
-- =========================================================

'Among all refunded orders, how many had an SLA breach? 
Refunded orders with SLA breach / Total refunded orders
'
with cte AS (
Select o.order_id as total_order,
promised_delivery_date,
DATE(adjusted_stage_end_time) as actual_delivery_date,
r.order_id as return_order,
Case 
 	When DATE(adjusted_stage_end_time) > promised_delivery_date Then 1 Else 0 End as sla_breach
from orders o
Join ops.fulfilment_events_clean f
on o.order_id = f.order_id
left join returns r
on r.order_id = o.order_id
WHere f.stage_name = 'Delivery'
And adjusted_stage_end_time is not null
AND r.order_id is not null)

Select sla_breach,
SUM(sla_breach) as return_orders,
COUNT(distinct total_order) as total_orders,
ROUND(100.0 * SUM(sla_breach) / COUNT(distinct total_order),2) as return_rate
From cte 
Group by 1



-- =========================================================
-- Q38.	Margin impact of returns by hub?
-- =========================================================
  
'When an order is returned:

Revenue is effectively lost
Shipping cost is still incurred
So margin becomes negative impact.
margin = order_value - shipping_cost'

with cte as (
Select o.order_id,
o.hub_id,
h.hub_name,
order_value,
shipping_cost,
refund_amount,
(order_value - shipping_cost) as order_margin,
Case when r.return_id is not null then 1 Else 0 End as return_flag

FROM orders o
JOIN shipping s
    ON s.order_id = o.order_id
JOIN hubs h
    ON h.hub_id = o.hub_id
LEFT JOIN returns r
    ON r.order_id = o.order_id
	Order by 1)

Select 
hub_name,
SUM(return_flag) as returned_orders,
COUNT(order_id) as total_orders,
ROUND(SUM(order_margin),2) as total_margin_generated,
SUM(case when return_flag = 1 then order_margin end) as margin_lost_return
from cte
Group by 1
order by 5 DESC;



-- =========================================================
-- 🔹 E. Early Warning & Strategic Insights (39–45)
-- 39.	Leading indicator of SLA breach (which stage delay predicts it)?
-- =========================================================

-- If a stage exceeds its SLA early in the pipeline, does it predict a delivery breach later?

'Compute stage duration
Compare with stage SLA
Flag stage breaches
Identify orders with final delivery breach
Check which stage breaches occur most frequently before those delivery breaches'

WIth stage_performance As (
Select -- step 1 & 2 & 3
o.order_id,
o.order_date,
f.stage_name,
ROUND(EXTRACT(EPOCH FROM(adjusted_stage_end_time - stage_start_time))/3600,2) as time_diff,
Case 
	When ROUND(EXTRACT(EPOCH FROM(adjusted_stage_end_time - stage_start_time))/3600,2) > sla_hours 
	Then 1 else 0 End as sla_breach,
sla_hours
from orders o 
JOIN ops.fulfilment_events_clean f
on o.order_id = f.order_id
join sla s
on s.stage_name = f.stage_name
Where adjusted_stage_end_time is not null
order by order_id),


delivery_breach as (
Select -- step 4 Identify orders with final delivery breach
o.order_id,
CASE 
WHEN DATE(f.adjusted_stage_end_time) > o.promised_delivery_date THEN 1 ELSE 0
    END AS delivery_breach_flag
From orders o
Join ops.fulfilment_events_clean f
on o.order_id = f.order_id
Where stage_name = 'Delivery'
And adjusted_stage_end_time is not null) 

Select
stage_name,
COUNT(*) as sla_breaches_before_delivery_breach
From stage_performance s
JOin delivery_breach d
on s.order_id = d.order_id
WHere s.sla_breach = 1
And d.delivery_breach_flag = 1
AND s.stage_name <> 'Delivery' -- filter to only those orders where stage wise par bhi sla breach hua 
-- and final delivery par bhi sla breach hua 
Group by 1
Order by 2 Desc;

-- If QC exceeds SLA, the order is very likely to miss delivery promise.



-- =========================================================
-- Q40.	Does QC duration spike precede backlog formation?
-- =========================================================

'Does QC becoming slow cause backlog later?
Orders that are not completed yet but should have been completed already. 
Because operations pipeline looks like this:

Intake → QC → Packing → Shipping → Delivery 
We are verifyingi if qc is the reason for the backlogs'

Select * from sla;
Select * from hubs;

-- step 1: 1️ Measure average QC duration per day
WIth qc_per_day as (
Select 
DATE(stage_start_time) as qc_date,
ROUND(AVG(EXTRACT(Epoch From(adjusted_stage_end_time - stage_start_time))/3600),2) as avg_qc_duration
From orders o
Join ops.fulfilment_events_clean f
On o.order_id = f.order_id
Where stage_name = 'QC'
AND adjusted_stage_end_time IS NOT NULL
Group by 1),

-- Step 2: Measure daily backlog size ( will find out those orders which are not delivered
-- We can use NOT IN or NOT EXISTS in this case )

delivery_backlogs as (
Select order_date,
COUNT(DISTINCT order_id) as backlog_orders
from orders o
Where NOT EXISTS (

Select 1
From ops.fulfilment_events_clean f
Where f.order_id = o.order_id
AND stage_name = 'Delivery'
AND adjusted_stage_end_time IS NOT NULL
) 
AND order_date < NOW() - Interval '48 hours' -- to consider backlog the order should be placed more than 48 hours ago
-- AND NOW() - order_date > INTERVAL '48 hours' 
-- And order_date <  DATE_SUB(NOW(), Interval 48 HOUR) MY SQL syntax
Group by 1)

-- step 3: Compare whether QC spikes happen before backlog days
Select qc_date, 
avg_qc_duration,
COALESCE(backlog_orders,0) as backlogs
from qc_per_day q
Left Join delivery_backlogs d
ON q.qc_date = d.order_date
WHere COALESCE(backlog_orders,0) >= 2
Order by 1
;
'“QC duration spikes appear to precede backlog formation, 
suggesting QC capacity constraints may be the primary driver of downstream congestion.”'



-- =========================================================
-- Q41.	If demand increases 20%, which hub breaks first?
-- =========================================================
  
'This is a capacity planning / stress-testing question. 
It’s a bit different from the previous ones because it’s hypothetical.'

-- Step 1 Calculate average daily throughput per hub
-- 2️⃣ Multiply demand by 1.2
-- 3️⃣ Compare with hub capacity

with daily_throughput as (
Select hub_id,
DATE(adjusted_stage_end_time) as processing_date,
COUNT(Distinct order_id) as orders_processed
from ops.fulfilment_events_clean 
Where stage_name = 'Delivery'
AND adjusted_stage_end_time IS NOT NULL
Group by 1,2
),

avg_throughput as (
Select
hub_id,
ROUND(AVG(orders_processed),2) as avg_daily_throughput
from daily_throughput
Group by 1
)

Select
t.hub_id,
h.hub_name,
avg_daily_throughput as current_Demand,
ROUND(1.2* avg_daily_throughput,2) as projected_demand,
capacity_per_day,
ROUND(100.0 * (1.2* avg_daily_throughput) / capacity_per_day,2) as utilization_pct

from avg_throughput t
JOIN hubs h
ON t.hub_id = h.hub_id;


'It helps operations decide:
where to increase capacity
which hubs need staffing
where to reroute orders'

  

-- =========================================================
-- Q42.	What is required capacity increase to maintain SLA?
-- =========================================================

'If hubs are currently operating near or above capacity and causing SLA breaches, 
how much extra capacity is required so utilisation stays within a safe range.
Operations usually try to keep utilisation around: 80–85%

Because: Above 90% → risk of delays
Above 100% → backlog
So the question becomes: What additional capacity is needed so utilisation stays ≤ 85%.
current_utilization = demand / capacity
required_capacity = demand / target_utilization
capacity_increase = required_capacity - current_capacity'

-- step 1 find current utilization_pct of hubs 

with daily_throughput as (
Select hub_id,
DATE(adjusted_stage_end_time) as processing_date,
COUNT(Distinct order_id) as orders_processed
from ops.fulfilment_events_clean 
Where stage_name = 'Delivery'
AND adjusted_stage_end_time IS NOT NULL
Group by 1,2
),

avg_throughput as (
Select
hub_id,
ROUND(AVG(orders_processed),2) as avg_daily_throughput
from daily_throughput
Group by 1
)

Select
t.hub_id,
h.hub_name,
avg_daily_throughput as current_Demand,
capacity_per_day,
ROUND(100.0 * (avg_daily_throughput) / capacity_per_day,2) as current_utilization_pct,
ROUND(avg_daily_throughput / 0.85,2) as required_capacity_per_day,
ROUND((avg_daily_throughput / 0.85) - capacity_per_day,2) as capacity_increase_needed
from avg_throughput t
JOIN hubs h
ON t.hub_id = h.hub_id;

-- in our case we can reduce the capacity_per_day in each hub because they are under utilized 



-- =========================================================
-- Q43.	Which hub should receive operational investment?
-- =========================================================

'A hub that needs investment usually has:

Metric	Meaning
High SLA breach rate	Reliability problem
High utilisation	Capacity constraint
High backlog	Demand exceeds supply
High processing variability	Operational instability

The hub that scores worst across these metrics should receive investment.'
'SLA breaches are two types in this case 
1st when deluvery date is > than promised delivery date
2nd when stage order processing_duration is > than sla_hours'

'Example Approach

We combine:

1️⃣ SLA breach rate -- reliabilty problem (delivery dtae > promised_date)
2️⃣ Capacity utilisation - stress level
3️⃣ Backlog orders -- operational congestion (orders that still need to be processed )

Then rank hubs.'

-- first we will check delivery level sla breaches
with cte1  AS (
Select o.hub_id,
hub_name,
COUNT(distinct o.order_id) as total_orders,
SUM(CASE WHEN DATE(adjusted_stage_end_time) > promised_delivery_date Then 1 else 0 end) as sla_breach,
ROUND(100.0 * SUM(CASE WHEN DATE(adjusted_stage_end_time) > promised_delivery_date Then 1 else 0 end) /
COUNT(distinct o.order_id),2) as sla_breach_rate
from orders o 
Join ops.fulfilment_events_clean f
on o.order_id = f.order_id
Join hubs h
on h.hub_id = o.hub_id
WHERE f.stage_name = 'Delivery'
AND f.adjusted_stage_end_time IS NOT NULL
Group by 1,2),

-- second will check for high backlog
cte2 AS (
SELECT
    hub_id,
    COUNT(order_id) AS backlog_orders
FROM (
    SELECT 
        o.order_id,
        o.order_date,
        o.hub_id
    FROM orders o
    WHERE NOT EXISTS (
        SELECT 1
        FROM ops.fulfilment_events_clean f
        WHERE f.order_id = o.order_id
        AND f.stage_name = 'Delivery'
        AND f.adjusted_stage_end_time IS NOT NULL
    )
    AND o.order_date < NOW() - INTERVAL '48 hours'
) AS a
GROUP BY hub_id
),
 -- to only consider orders that are 48 hours ag0 placed ,

-- step 3 check for capacity_utilization
daily_throughput as (
Select
o.hub_id,
DATE(adjusted_stage_end_time) as processing_date,
COUNT(*) as daily_troughput
from orders o
Join ops.fulfilment_events_clean f
on o.order_id = f.order_id
AND stage_name = 'Delivery'
AND f.adjusted_stage_end_time IS NOT NULL
Group by 1,2
order by 1),

avg_throughput as (
Select
hub_id,
ROUND(Avg(daily_troughput),2) as avg_daily_throughput
from daily_throughput
Group by 1
)


Select t.hub_id,
h.hub_name,
total_orders,
sla_breach_rate,
backlog_orders,
ROUND(100.0 * avg_daily_throughput / capacity_per_day,2) as utilizations_pct
from avg_throughput t
join cte1 as c1
ON c1.hub_id = t.hub_id
Join cte2 as c2
ON c2.hub_id = t.hub_id
Join hubs h
on h.hub_id = t.hub_id;



-- =========================================================
-- Q44.	If we reduce QC time by 15%, what happens to SLA?
-- =========================================================

with cte as (
Select order_id,
sla_hours,
Round(Extract(epoch from (adjusted_stage_end_time - stage_start_time))/3600,2) as processing_time,
Round(0.85*Extract(epoch from (adjusted_stage_end_time - stage_start_time))/3600,2) as new_processing_time
from ops.fulfilment_events_clean f
JOin sla s
on s.stage_name = f.stage_name
Where s.stage_name = 'QC'
and adjusted_stage_end_time is not null),

cte1 as(
select *,
Case When processing_time > sla_hours then 1 else 0 end as old_breach,
Case When new_processing_time > sla_hours then 1 else 0 end as new_breach
from cte
)

Select 
COUNT(*)as total_orders,
Sum(old_breach) as old_breaches,
Sum(new_breach) as updated_breaches
From cte1;



-- =========================================================
-- Q45.	What is biggest cost driver in fulfilment pipeline?
-- =========================================================

'In your dataset, cost can be approximated by:
processing_time × operational cost rate
Since we don’t have labor cost per stage, the best proxy is:
Total processing hours spent in each stage
The stage consuming the most total time is likely the biggest cost driver.'

WITH stage_time AS (
SELECT
    stage_name,
    EXTRACT(EPOCH FROM (adjusted_stage_end_time - stage_start_time))/3600 AS processing_hours
FROM ops.fulfilment_events_clean
WHERE adjusted_stage_end_time IS NOT NULL
)

SELECT
stage_name,
COUNT(*) AS total_events,
ROUND(AVG(processing_hours),2) AS avg_processing_hours,
ROUND(SUM(processing_hours),2) AS total_processing_hours
FROM stage_time
GROUP BY stage_name
ORDER BY total_processing_hours DESC;
